package com.mycompany.internshipmanager.std_dashboard;

import com.mycompany.internshipmanager.std_dashboard.ViewApplication;
import com.mycompany.internshipmanager.emp_dashboard.ViewApplicationsList;
import com.mycompany.internshipmanager.models.Application;
import com.mycompany.internshipmanager.models.Internship;
import com.mycompany.internshipmanager.models.Student;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Asus
 */
public class ApplicationItem extends javax.swing.JPanel {

    /**
     * Creates new form ApplicationItem
     */
    public ApplicationItem(Internship intern, Application appl, std_dashboard parent) {
        initComponents();
        
        Dimension itemPanelSize = new Dimension(608,50);
        setLayout(new MigLayout("fill, insets 10", "[33%][33%][33%]", "[]"));
        setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        setPreferredSize(itemPanelSize);
        setMinimumSize(itemPanelSize);
        setMaximumSize(itemPanelSize);
        setBackground(Color.decode("#556270"));

        addMouseListener(new MouseAdapter(){
            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                setBackground(Color.white);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                setBackground(Color.decode("#556270"));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                parent.gp.setVisible(true);
                new ViewApplication(appl, parent).setVisible(true);                
            }



        });
        
        add(new JLabel(truncateText(intern.getTitle(), 20)){{
            setForeground(Color.black);
            setFont(getFont().deriveFont(16f));
        }}, "cell 0 0");
        add(new JLabel(truncateText(appl.getDate(), 12)){{setForeground(Color.black);setForeground(Color.black);setFont(getFont().deriveFont(16f));}}, "cell 1 0");
        add(new JLabel(truncateText(appl.getStatus(),15)){{
            if (appl.getStatus().equals("To be reviewed")){
                setForeground(Color.decode("#F4BB44"));
            } else if (appl.getStatus().equals("Accepted")){
                setForeground(Color.green);
            } else if (appl.getStatus().equals("Rejected")){
                setForeground(Color.red);
            }
            setFont(getFont().deriveFont(Font.BOLD, 16f));}}, "cell 2 0");
    }
    
    public static String truncateText(String text, int maxLength) {
        if (text.length() > maxLength) {
            return text.substring(0, maxLength - 3) + "...";
        }
        return text;
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
