package com.mycompany.internshipmanager.std_dashboard;

import com.mycompany.internshipmanager.controllers.EmployerController;
import com.mycompany.internshipmanager.emp_dashboard.ViewApplication;
import com.mycompany.internshipmanager.emp_dashboard.ViewApplicationsList;
import com.mycompany.internshipmanager.models.Application;
import com.mycompany.internshipmanager.models.Internship;
import com.mycompany.internshipmanager.models.Student;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Asus
 */
public class InternshipItem extends javax.swing.JPanel {

    /**
     * Creates new form ApplicationItem
     */
    private EmployerController empControl;
    
    public InternshipItem(Internship intern, std_dashboard dash) {
        initComponents();
        
        Dimension itemPanelSize = new Dimension(600,50);
        setLayout(new MigLayout("fill, insets 10", "[33%][33%][33%]", "[]"));
        setBorder(BorderFactory.createLineBorder(Color.black));
        setPreferredSize(itemPanelSize);
        setMinimumSize(itemPanelSize);
        setMaximumSize(itemPanelSize);
        setBackground(Color.decode("#556270"));

        addMouseListener(new MouseAdapter(){
            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                setBackground(Color.white);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                setBackground(Color.decode("#556270"));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                dash.gp.setVisible(true);
                new ViewInternship(intern, dash, true).setVisible(true);
            }



        });
        
        add(new JLabel(intern.getTitle()){{setForeground(Color.black);}}, "cell 0 0");
        add(new JLabel("Duration: "+String.valueOf(intern.getDuration())){{setForeground(Color.black);}}, "cell 1 0");
        add(new JLabel(intern.getStatus()){{setForeground(Color.black);}}, "cell 2 0");
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
