package com.mycompany.internshipmanager.std_dashboard;

import com.mycompany.internshipmanager.emp_dashboard.emp_dashboard;
import com.mycompany.internshipmanager.models.EmployerLoginDAO;
import com.mycompany.internshipmanager.models.StudentLoginDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form Login
     */
    private StudentLoginDAO StdDao;
    private EmployerLoginDAO EmpDao;
    
    public Login() {        
        initComponents();
        
        this.StdDao = new StudentLoginDAO();
        this.EmpDao = new EmployerLoginDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        password = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        role = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(632, 402));
        setMinimumSize(new java.awt.Dimension(632, 402));
        setPreferredSize(new java.awt.Dimension(632, 402));
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 140, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new java.awt.BorderLayout());

        email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(email, java.awt.BorderLayout.PAGE_START);

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 510, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new java.awt.BorderLayout());

        password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(password, java.awt.BorderLayout.PAGE_START);

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 510, 60));

        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButton.setText("Sign In");
        loginButton.setMaximumSize(new java.awt.Dimension(80, 30));
        loginButton.setMinimumSize(new java.awt.Dimension(80, 30));
        loginButton.setPreferredSize(new java.awt.Dimension(80, 30));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        panel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Role", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new java.awt.BorderLayout());

        role.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Employer" }));
        jPanel3.add(role, java.awt.BorderLayout.PAGE_START);

        panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, 60));

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String em = email.getText();
        String pass = password.getText();        
        
        
        if(role.getSelectedItem().equals("Student")){
            if (em.isEmpty() || pass.isEmpty()){
                JOptionPane.showMessageDialog(Login.this, "Empty email or password", "Input Error" ,JOptionPane.ERROR_MESSAGE);
                return;
            }

            try{
                String passwordInDb = this.StdDao.getPasswordByEmail(em);
                if (pass.equals(passwordInDb)){
                    //logging in
                    Login.this.dispose();
                    int id = this.StdDao.getIdByEmail(em);
                    
                    new std_dashboard(id).setVisible(true);
                    
                } else {
                    JOptionPane.showMessageDialog(Login.this, "Incorrect Password", "Input Error" ,JOptionPane.ERROR_MESSAGE);
                }
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(Login.this, ex.getMessage(), "Input Error" ,JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(role.getSelectedItem().equals("Employer")){
            if (em.isEmpty() || pass.isEmpty()){
                JOptionPane.showMessageDialog(Login.this, "Empty email or password", "Input Error" ,JOptionPane.ERROR_MESSAGE);
                return;
            }

            try{
                String passwordInDb = this.EmpDao.getPasswordByEmail(em);
                if (pass.equals(passwordInDb)){
                    //logging in
                    Login.this.dispose();
                    int id = this.EmpDao.getIdByEmail(em);
                    
                    new emp_dashboard(id).setVisible(true);
                    
                } else {
                    JOptionPane.showMessageDialog(Login.this, "Incorrect Password", "Input Error" ,JOptionPane.ERROR_MESSAGE);
                }
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(Login.this, ex.getMessage(), "Input Error" ,JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> role;
    // End of variables declaration//GEN-END:variables
}
