package com.mycompany.internshipmanager.std_dashboard;

import com.mycompany.internshipmanager.controllers.EmployerController;
import com.mycompany.internshipmanager.controllers.InternshipController;
import com.mycompany.internshipmanager.models.Employer;
import com.mycompany.internshipmanager.models.Internship;
import com.mycompany.internshipmanager.models.Placement;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Asus
 */
public class ViewPlacement extends javax.swing.JDialog {

    /**
     * Creates new form ViewPlacement
     */
    private std_dashboard parent;
    private Placement placement;
    private InternshipController internControl = new InternshipController();
    private EmployerController empControl = new EmployerController();
    
    public ViewPlacement(std_dashboard parent, Placement p) {
        super(parent, true);
        initComponents();
        
        this.parent = parent;
        this.placement = p;
        
        Internship intern = internControl.getInternshipByID(placement.getInternship_id());
        Employer emp = empControl.getEmployerByID(placement.getEmp_id());
        
        internName1.setText(intern.getTitle());
        empName.setText(emp.getName());
        duration1.setText(p.getStart_date() + " - " + p.getEnd_date());
        status1.setText(p.getStatus());
        
        empNamePanel.setBackground(Color.decode("#484848"));
        empNamePanel.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                new ViewEmployer(intern.getEmp_id(), ViewPlacement.this).setVisible(true);
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                empNamePanel.setBackground(Color.decode("#585858"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                empNamePanel.setBackground(Color.decode("#484848"));
            }
            
            
            
        });
        
        setLocationRelativeTo(parent);
        
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e) {
                super.windowClosed(e);
                parent.gp.setVisible(false);
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        empNamePanel = new javax.swing.JPanel();
        empName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        internName1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        duration1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        status1 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(604, 522));
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("Internship");
        panel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 180, 60));

        empNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employer Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        empNamePanel.setLayout(new java.awt.BorderLayout());

        empName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        empName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empName.setText("Name");
        empNamePanel.add(empName, java.awt.BorderLayout.CENTER);

        panel.add(empNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 530, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Internship Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new java.awt.BorderLayout());

        internName1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        internName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internName1.setText("Name");
        jPanel3.add(internName1, java.awt.BorderLayout.CENTER);

        panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 530, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duration", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new java.awt.BorderLayout());

        duration1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        duration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        duration1.setText("Duration");
        jPanel4.add(duration1, java.awt.BorderLayout.CENTER);

        panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 530, 70));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel5.setLayout(new java.awt.BorderLayout());

        status1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status1.setText("Status");
        jPanel5.add(status1, java.awt.BorderLayout.CENTER);

        panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 530, 70));

        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeButton.setText("Close");
        closeButton.setMaximumSize(new java.awt.Dimension(80, 30));
        closeButton.setMinimumSize(new java.awt.Dimension(80, 30));
        closeButton.setPreferredSize(new java.awt.Dimension(80, 30));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        panel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 100, 40));

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        ViewPlacement.this.dispose();        
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel duration1;
    private javax.swing.JLabel empName;
    private javax.swing.JPanel empNamePanel;
    private javax.swing.JLabel internName1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
