package com.mycompany.internshipmanager.emp_dashboard;

import com.mycompany.internshipmanager.controllers.StudentController;
import com.mycompany.internshipmanager.models.Student;
import com.mycompany.internshipmanager.std_dashboard.StudentReport;
import javax.swing.JDialog;

/**
 *
 * @author Asus
 */
public class ViewStudent extends javax.swing.JDialog {

    private StudentController stdControl;
    private JDialog parent;
    private int std_id;
    
    public ViewStudent(JDialog parent, int id) {
        super(parent, true);
        initComponents();
        
        this.parent = parent;
        this.std_id = id;
        
        stdControl = new StudentController();
        Student std = stdControl.getStudentByID(id);
        
        fname.setText(std.getFirst_name());
        lname.setText(std.getLast_name());
        dob.setText(std.getDob());
        email.setText(std.getEmail());
        phone.setText(std.getPhone());
        department.setText(std.getDepartment());
        yos.setText(String.valueOf(std.getYearOfStudy()));
        
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fname = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lname = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dob = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        phone = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        department = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        yos = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(537, 572));
        setMinimumSize(new java.awt.Dimension(537, 572));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(537, 572));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Student Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 260, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new java.awt.BorderLayout());

        fname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fname.setText("Name");
        jPanel2.add(fname, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 460, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lname.setText("Name");
        jPanel3.add(lname, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 460, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date of Birth", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new java.awt.BorderLayout());

        dob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dob.setText("DOB");
        jPanel4.add(dob, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 460, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel5.setLayout(new java.awt.BorderLayout());

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("Email");
        jPanel5.add(email, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 460, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel6.setLayout(new java.awt.BorderLayout());

        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phone.setText("Phone");
        jPanel6.add(phone, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 460, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel7.setLayout(new java.awt.BorderLayout());

        department.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        department.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        department.setText("Department");
        jPanel7.add(department, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 460, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Year of Study", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel8.setLayout(new java.awt.BorderLayout());

        yos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yos.setText("YOS");
        jPanel8.add(yos, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, -1));

        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeButton.setText("Close");
        closeButton.setMaximumSize(new java.awt.Dimension(80, 30));
        closeButton.setMinimumSize(new java.awt.Dimension(80, 30));
        closeButton.setPreferredSize(new java.awt.Dimension(80, 30));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 100, 40));

        reportButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportButton.setText("View Report");
        reportButton.setMaximumSize(new java.awt.Dimension(80, 30));
        reportButton.setMinimumSize(new java.awt.Dimension(80, 30));
        reportButton.setPreferredSize(new java.awt.Dimension(80, 30));
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 150, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        new StudentReport(std_id, ViewStudent.this);
    }//GEN-LAST:event_reportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel department;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel phone;
    private javax.swing.JButton reportButton;
    private javax.swing.JLabel yos;
    // End of variables declaration//GEN-END:variables
}
