package com.mycompany.internshipmanager.employer_views;

import com.mycompany.internshipmanager.student_views.*;
import com.mycompany.internshipmanager.NavHistory;
import com.mycompany.internshipmanager.controllers.EmployerController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;
import com.mycompany.internshipmanager.controllers.StudentController;
import com.mycompany.internshipmanager.custom_ui.BackButton;
import com.mycompany.internshipmanager.models.Employer;
import com.mycompany.internshipmanager.models.Student;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Stack;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

/**
 *
 * @author Asus
 */
public class EmployerDetails extends javax.swing.JPanel {

    /**
     * Creates new form EmployerDetails
     */
    Employer emp;
    EmployerController con;
    
    
    public EmployerDetails(int id) {
        initComponents();
        
        this.con = new EmployerController();
        this.emp =  con.getEmployerByID(id); 
        
        
        setLayout(new MigLayout("fill, flowy"));
        
        JPanel titlePanel = new JPanel(new MigLayout("fillx", "[33%][33%][33%]"));
        JPanel contentPanel = new JPanel(new MigLayout("wrap 2, fillx", "[]15[]", "[]15[]"));
        JPanel buttonPanel = new JPanel();
        
        JLabel title = new JLabel("Employer Details"); //setting up the title
        ;
        BackButton back = new BackButton("<-", this);        //back button
        
        titlePanel.add(back, "align left, cell 0 0");
        titlePanel.add(title, "cell 1 0, span 2");
        add(titlePanel, "dock north");
        
        contentPanel.add(new JLabel("Employer ID: "), "align label");
        contentPanel.add(new JLabel(String.valueOf(emp.getEmp_id())), "growx, wrap");
        
        contentPanel.add(new JLabel("Company Name: "), "align label");
        contentPanel.add(new JLabel(emp.getName()), "growx, wrap");
        
        contentPanel.add(new JLabel("Email: "), "align label");
        contentPanel.add(new JLabel(emp.getEmail()), "growx, wrap");
        
        contentPanel.add(new JLabel("Contact Number: "), "align label");
        contentPanel.add(new JLabel(emp.getPhone()), "growx, wrap");
        
        contentPanel.add(new JLabel("Description: "), "growx, align label");
        JTextArea textarea = new JTextArea(4, 20);
        textarea.setLineWrap(true);
        textarea.setWrapStyleWord(true);
        textarea.setText(emp.getDescription());
        textarea.setEditable(false);
        
        JScrollPane scroll = new JScrollPane(textarea, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        contentPanel.add(scroll, "growx, wrap");
        
        contentPanel.add(new JLabel("Industry: "), "align label");
        contentPanel.add(new JLabel(emp.getIndustry()), "growx, wrap");
        
        add(contentPanel);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
