package com.mycompany.internshipmanager.student_views;

import com.mycompany.internshipmanager.NavHistory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;
import com.mycompany.internshipmanager.controllers.StudentController;
import com.mycompany.internshipmanager.custom_ui.BackButton;
import com.mycompany.internshipmanager.models.Student;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Stack;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Asus
 */
public class StudentDetails extends javax.swing.JPanel {

    /**
     * Creates new form StudentDetails
     */
    Student std;
    StudentController con;
    StudentDetails referencecopy;
    
    public StudentDetails(int id) {
        initComponents();
        
        this.con = new StudentController();
        this.std =  con.getStudentByID(id); 
        this.referencecopy = this;
        
        setLayout(new MigLayout("fill, flowy"));
        
        JPanel titlePanel = new JPanel(new MigLayout("fillx", "[33%][33%][33%]"));
        JPanel contentPanel = new JPanel(new MigLayout("wrap 2", "[]15[]", "[]15[]"));
        JPanel buttonPanel = new JPanel();
        
        JLabel title = new JLabel("Student Details"); //setting up the title
        ;
        BackButton back = new BackButton("<-", this);        
        
        titlePanel.add(back, "align left, cell 0 0");
        titlePanel.add(title, "cell 1 0, span 2");
        add(titlePanel, "dock north");
        
        contentPanel.add(new JLabel("Student ID: "), "align label");
        contentPanel.add(new JLabel(String.valueOf(std.getStd_id())), "wrap");
        
        contentPanel.add(new JLabel("Student Name: "), "align label");
        contentPanel.add(new JLabel(std.getFirst_name()+ " "+ std.getLast_name()), "wrap");
        
        contentPanel.add(new JLabel("Date of Birth: "), "align label");
        contentPanel.add(new JLabel(std.getDob()), "wrap");
        
        contentPanel.add(new JLabel("Email: "), "align label");
        contentPanel.add(new JLabel(std.getEmail()), "wrap");
        
        contentPanel.add(new JLabel("Contact: "), "align label");
        contentPanel.add(new JLabel(std.getPhone()), "wrap");
        
        contentPanel.add(new JLabel("Date of Birdth: "), "align label");
        contentPanel.add(new JLabel(std.getDob()), "wrap");
        
        contentPanel.add(new JLabel("Department: "), "align label");
        contentPanel.add(new JLabel(std.getDepartment()), "wrap");
        
        contentPanel.add(new JLabel("Year of Study: "), "align label");
        contentPanel.add(new JLabel(String.valueOf(std.getYearOfStudy())), "wrap");
        
        add(contentPanel);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
