package com.mycompany.internshipmanager.student_views;

import com.mycompany.internshipmanager.LoggedStudent;
import com.mycompany.internshipmanager.NavHistory;
import com.mycompany.internshipmanager.controllers.StudentController;
import com.mycompany.internshipmanager.custom_ui.BackButton;
import com.mycompany.internshipmanager.models.Student;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Stack;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;


public class StudentUpdateForm extends javax.swing.JPanel {

    
    private StudentController control;
    private Student std = LoggedStudent.getInstance().getStudent();
    
    
    public StudentUpdateForm() {
        initComponents();
        
        
        this.control = new StudentController();
        
        setLayout(new MigLayout("fill, flowy"));
        
        JPanel titlePanel = new JPanel(new MigLayout("fillx", "[33%][33%][33%]"));
        JPanel contentPanel = new JPanel(new MigLayout("wrap 2, fillx", "[]15[]", "[]15[]"));
        JPanel buttonPanel = new JPanel(new MigLayout("fillx", "[]20[]"));
        
        BackButton back = new BackButton("<-", this);       
        
        titlePanel.add(back, "cell 0 0, align left");        
        titlePanel.add(new JLabel("Update Student Profile"), "cell 1 0, align center"); //title                        
        
        add(titlePanel, "dock north");
        
        contentPanel.add(new JLabel("First Name: "), "align label"); //form
        JTextField fname = new JTextField(std.getFirst_name());
        contentPanel.add(fname, "growx, wrap");
        
        contentPanel.add(new JLabel("Second Name: "), "align label");
        JTextField lname = new JTextField(std.getLast_name());
        contentPanel.add(lname, "growx, wrap");
        
        contentPanel.add(new JLabel("Date (yyyy-MM-dd): "), "align label");
        JTextField date = new JTextField(std.getDob());
        contentPanel.add(date, "growx, wrap");
        
        contentPanel.add(new JLabel("Email: "), "align label");
        JTextField email = new JTextField(std.getEmail());
        contentPanel.add(email, "growx, wrap");
        
        contentPanel.add(new JLabel("Contact Number: "), "align label");
        JTextField phone = new JTextField(std.getPhone());
        contentPanel.add(phone, "growx, wrap");
        
        contentPanel.add(new JLabel("Department: "), "align label");
        JTextField dep = new JTextField(std.getDepartment());
        contentPanel.add(dep, "growx, wrap");
        
        contentPanel.add(new JLabel("Year of Study: "), "align label");
        JTextField yos = new JTextField(String.valueOf(std.getYearOfStudy()));
        contentPanel.add(yos, "growx, wrap");  
        
        add(contentPanel, "dock center");
        
        JButton register = new JButton("Update"); //buttons
        register.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                try{
                    control.updateStudent(std.getStd_id(),fname.getText(), lname.getText(), date.getText(), email.getText(), phone.getText(), dep.getText(), yos.getText());
                    Student newLogged = control.getStudentByID(std.getStd_id()); //updating the logged student
                    LoggedStudent.getInstance().setStudent(newLogged);
                    std = newLogged;
                } catch (IllegalArgumentException ex){
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        });
        buttonPanel.add(register, "align right");
        
        JButton close = new JButton("Close");
        close.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                System.exit(0);
            }
        });
        buttonPanel.add(close, "align left");
        
        add(buttonPanel, "dock south"); //button panel
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
