package com.mycompany.internshipmanager.views;

import com.mycompany.internshipmanager.NavHistory;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;


public class StudentItemPanel extends javax.swing.JPanel {       

    /**
     * Creates new form StudentItemPanel
     */
    private int id;
    private String name;
    private Color background_color; 
    private Color text_color;
    private StudentItemPanel referencecopy;
    
    public StudentItemPanel(int id, String name) {
        this.id = id;
        this.name = name;
        this.background_color = Color.WHITE;   
        this.text_color = Color.BLACK;;
        this.referencecopy = this;
        
        
        //setting custom layout
        setLayout(new MigLayout("fill"));
        setBackground(background_color);
        setPreferredSize(new Dimension(300, 50));
        
        //text
        JLabel lb = new JLabel("ID: " + id + "        Name: "+ name);
        lb.setForeground(text_color);
        add(lb, "align center, growx");
        
        //adding a mouse interactions
        addMouseListener(new MouseAdapter(){
            @Override
            public void mouseEntered(MouseEvent e){
                setBackground(Color.GRAY);
            }
            @Override
            public void mouseExited(MouseEvent e){
                setBackground(background_color);
            }
            
            @Override
            public void mouseClicked(MouseEvent e){
                //MOUSE CLICK EVENT
                //switching panes for the window
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(referencecopy);                 
                frame.getContentPane().removeAll();
                
                StudentDetails stdDetails = new StudentDetails(id);
                
                NavHistory.get().push(stdDetails);
                
                
                frame.add(stdDetails);
                frame.revalidate();
                frame.repaint();
            }
        });
        
       
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
